In [63]:
import pandas as pd
import numpy as np

In [64]:
data = pd.read_csv('/Users/skmishra19/Desktop/AI_ML/Bengaluru_House_Data.csv')

In [65]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [66]:
data.shape

(13320, 9)

In [67]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 936.7 KB

In [68]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
27 BHK           1
19 BHK           1
16 BHK           1
43 Bedroom       1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Maa 5a      1
AeisePV     1
SJovest     1
ThhtsV      1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
1020 - 1130      1
2758             1
1133 - 1384      1
774              1
4689             1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
96.80       1
63.93       1
40.14       1
231.00      1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [69]:
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [70]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [71]:
data.drop(columns=['area_type', 'society', 'balcony', 'availability'], inplace=True)

In [72]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [73]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  str
 1   size        13304 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [74]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [75]:
data['size'] = data['size'].fillna('0 BHK')

In [76]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [77]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  str
 1   size        13320 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [78]:
data['bhk'] = data['size'].str.split(' ').str.get(0).astype(int)

In [79]:
data[data.bhk > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [80]:
data['total_sqft'].unique()

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
 ...
        '3124',        '9200',         '613',         '250',        '2395',
 '1020 - 1130',        '2758', '1133 - 1384',         '774',        '4689']
Length: 2117, dtype: str

In [81]:
def convertRange(x):

    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [82]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)

In [83]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

Price Per Square Feet

In [84]:
data['price_per_sqft'] = data['price']*100000/data['total_sqft']

In [85]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [86]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.800375    7.907501e+03
std     1238.405258      1.338754    148.971674      1.297835    1.064296e+05
min        1.000000      1.000000      8.000000      0.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [87]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [88]:
data['location'] = data['location'].astype(str).str.strip()

In [89]:

location_count = data['location'].value_counts()

In [90]:
location_count_less_than_10 = location_count[location_count <= 10]

In [91]:
location_count_less_than_10

location
Ganga Nagar                                        10
Dairy Circle                                       10
Sadashiva Nagar                                    10
Naganathapura                                      10
Nagappa Reddy Layout                               10
                                                   ..
Pattegarhpalya                                      1
Tilak Nagar                                         1
12th cross srinivas nagar banshankari 3rd stage     1
Havanur extension                                   1
Abshot Layout                                       1
Name: count, Length: 1053, dtype: int64

In [92]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_count_less_than_10 else x)

Outlier detection and removal

In [93]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.800375    7.907501e+03
std     1238.405258      1.338754    148.971674      1.297835    1.064296e+05
min        1.000000      1.000000      8.000000      0.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [94]:
(data['total_sqft']/data['bhk']).describe()

/opt/anaconda3/envs/ml_env/lib/python3.11/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    1.327400e+04
mean              inf
std               NaN
min      2.500000e-01
25%      4.733333e+02
50%      5.525000e+02
75%      6.250000e+02
max               inf
dtype: float64

In [95]:
data = data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.648284     6303.979357
std     1261.271296      1.077938    152.077329      0.980982     4162.237981
min      300.000000      1.000000      8.440000      0.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [96]:
data.shape

(12530, 7)

In [97]:
data.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [98]:
def remove_outliers_sqft(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out
data = remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10300.000000  10300.000000  10300.000000  10300.000000    10300.000000
mean    1508.431719      2.471650     91.286885      2.573883     5659.090455
std      880.736507      0.979483     86.346962      0.899384     2265.883017
min      300.000000      1.000000     10.000000      0.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.864208
50%     1286.000000      2.000000     67.000000      2.000000     5175.519668
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [99]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
    return df.drop(exclude_indices, axis='index')
data = bhk_outlier_remover(data)
data.describe()

         total_sqft         bath        price          bhk  price_per_sqft
count   7362.000000  7362.000000  7362.000000  7362.000000     7362.000000
mean    1497.197223     2.447840    99.086595     2.499049     6126.833986
std      866.149094     1.011446    93.334743     0.931457     2409.524371
min      300.000000     1.000000    10.000000     0.000000     1300.000000
25%     1096.000000     2.000000    50.000000     2.000000     4600.000000
50%     1260.000000     2.000000    73.000000     2.000000     5679.506173
75%     1680.000000     3.000000   113.000000     3.000000     6896.551724
max    30000.000000    16.000000  2200.000000    16.000000    24509.803922

In [100]:
data = bhk_outlier_remover(data)

In [101]:
data.shape

(6801, 7)

In [102]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10291,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10292,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10295,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10296,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10299,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [103]:
data.drop(columns=['size', 'price_per_sqft'], inplace=True)

Cleaned Data

In [104]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [105]:
data.to_csv('/Users/skmishra19/Desktop/AI_ML/cleaned_bangalore_house_data.csv', index=False)

In [106]:
X = data.drop(columns=['price'])
y = data['price']

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [109]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5440, 4) (1361, 4) (5440,) (1361,)

In [110]:
print(X_test.shape)

(1361, 4)

Applying Linear Regression

In [111]:
column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), ['location']),
    remainder='passthrough'
)

In [112]:
scaler = StandardScaler()

In [113]:
lr = make_pipeline(StandardScaler(), LinearRegression())

In [ ]:
pipe = make_pipeline(preprocessor, column_trans, scaler, lr)

In [ ]:
y_pred_ridge = pipe.predict(X_test)
#r2_score(y_test, y_pred_ridge)

In [128]:
import pickle

In [129]:
pickle.dump(pipe, open('RidgeModel.pkl', 'wb'))